//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCBIZTECHApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftwareServiceRequest
    {
        public System.Guid RequestId { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string YourCompany { get; set; }
        public string YourTitle { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public string ServiceRequested { get; set; }
        public string Message { get; set; }
    }
}
